apiVersion: v1
kind: LimitRange
metadata:
  name: default-limitrange
  namespace: cert-manager
spec:
  limits:
    - default:
        cpu: 100m
        memory: 128Mi
      defaultRequest:
        cpu: 10m
        memory: 64Mi
      max:
        cpu: 100m
        memory: 128Mi
      type: Container
