apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - thule-autoscaler.yaml
  - thule-configmap.yaml
  - thule-deployment.yaml
  # - thule-networkpolicy.yaml
  - thule-service.yaml
