apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: thule
spec:
  maxReplicas: 10
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: thule
  targetCPUUtilizationPercentage: 50
