apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/kubernetes-sigs/external-dns//kustomize
  - limitrange.yaml
  - namespace.yaml
patchesStrategicMerge:
  - externaldns-clusterrole.yaml
  - externaldns-deployment.yaml
namespace: external
