apiVersion: v1
kind: LimitRange
metadata:
  name: default-limitrange
spec:
  limits:
    - default:
        cpu: 500m
        memory: 386Mi
      defaultRequest:
        cpu: 10m
        memory: 64Mi
      max:
        cpu: 500m
        memory: 386Mi
      type: Container
