apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-acme
spec:
  podSelector: {}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: projectcontour
      ports:
        - port: 8089
