apiVersion: v1
kind: ConfigMap
metadata:
  name: dg-lite-nginx-config
data:
  default: |
    server {
        listen       8080;
        listen  [::]:8080;
        server_name  localhost;

        location / {
            root   /app;
            try_files $uri $uri/ /index.html;
        }
    }
