apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: dg-lite
spec:
  maxReplicas: 10
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dg-lite
  targetCPUUtilizationPercentage: 50
