apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ../../base/
  - ./dg-lite-db-01/dg-lite-db01-secret.yaml
  - ./dg-lite-frontend/dg-lite-frontend-ingress.yaml
  - ./thule/thule-ingress.yaml
  - ./thule/thule-secretmap.yaml
patchesStrategicMerge:
  - ./dg-lite-frontend/dg-lite-frontend-configmap.yaml
  - ./dg-lite-frontend/dg-lite-frontend-deployment.yaml
  - ./thule/thule-configmap.yaml
  - ./thule/thule-deployment.yaml
namespace: prod
