apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: dglite-db-01
spec:
  members: 3
  type: ReplicaSet
  version: "5.0.6"
  security:
    authentication:
      modes: ["SCRAM"]
  statefulSet:
    spec:
      template:
        spec:
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: ScheduleAnyway
              labelSelector:
                matchLabels:
                  app: dglite-db-01-svc
          containers:
            - name: "mongodb-agent"
              resources:
                requests:
                  cpu: 20m
                  memory: 64Mi
                limits:
                  cpu: 500m
                  memory: 256Mi
            - name: "mongod"
              resources:
                requests:
                  memory: "256Mi"
                  cpu: "50m"
                limits:
                  memory: "768Mi"
                  cpu: "500m"
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 1Gi
        - metadata:
            name: logs-volume
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 100Mi
  users:
    - name: my-user
      db: admin
      passwordSecretRef:
        name: dglitedb01-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
        - name: readWrite
          db: dglite-db-01
      scramCredentialsSecretName: my-scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
