apiVersion: apps/v1
kind: Deployment
metadata:
  name: dg-lite-frontend
spec:
  selector:
    matchLabels:
      io.kompose.service: dg-lite-frontend
  template:
    spec:
      containers:
        - name: dg-lite-frontend
          image: 301922485551.dkr.ecr.ap-southeast-2.amazonaws.com/dg-lite-frontend:production
