apiVersion: v1
kind: ConfigMap
metadata:
  name: thule-config
data:
  local.json: |
    {
        "server": {
            "trustProxy": true,
            "enableCsrf": true,
            "corsOrigins": ["https://app.dev.dg-lite.com", "https://dg-lite-aws.danward.me", "http://localhost:3000"]
        },
        "database": {
            "rawMongo": {
                "dbname": "dg-lite-backend",
                "urlprefix": "mongodb://",
                "username": "my-user",
                "urls": [
                    "dg-lite-backend-0.dg-lite-backend-svc.dev-01.svc:27017",
                    "dg-lite-backend-1.dg-lite-backend-svc.dev-01.svc:27017",
                    "dg-lite-backend-2.dg-lite-backend-svc.dev-01.svc:27017"
                ]
            }
        },
        "security": {
            "oauth": {
                "jwksClientConfig": {
                    "jwksUri": "https://cognito-idp.ap-southeast-2.amazonaws.com/ap-southeast-2_waPVCWL1F/.well-known/jwks.json"
                },
                "options": {
                    "iss": "https://cognito-idp.ap-southeast-2.amazonaws.com/ap-southeast-2_waPVCWL1F"
                }
            },
            "cognito": {
                "domain": "dg-lite-dev-01.auth.ap-southeast-2.amazoncognito.com",
                "clientId": "58lmov1sjr6vb1mg5sm3fgu85n",
                "poolId": "ap-southeast-2_waPVCWL1F",
                "redirectUri": "https://app.dev.dg-lite.com/authCallback",
                "logoutUri": "https://www.dg-lite.com",
                "region": "ap-southeast-2"
            }
        },
        "kms": {
            "keyId": "23fd669f-d24c-4e6c-8476-60a6e780642e",
            "region": "ap-southeast-2"
        },
        "ses": {
            "region": "ap-southeast-2",
            "verifiedIdentity": "noreply@dg-lite.com",
            "externalAddress": "https://api.dev.dg-lite.com"
        },
        "s3": {
            "buckets": {
                "profiledata": {
                    "bucketName": "dg-lite-dev-01",
                    "credentials": {},
                    "region": "ap-southeast-2"
                }
            }
        }
    }
