apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: thule
  name: thule
spec:
  selector:
    matchLabels:
      io.kompose.service: thule
  template:
    spec:
      containers:
        - name: thule
          image: 301922485551.dkr.ecr.ap-southeast-2.amazonaws.com/dglite-backend:production
          volumeMounts:
            - name: secrets
              mountPath: "/var/secrets/"
              readOnly: true
      volumes:
        - name: secrets
          secret:
            secretName: thule-secretmap
